name: Build
on: [workflow_call]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: "bash"

jobs:
  validation:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
